### ISSUE TITLE
Open Graph twitter data

### ISSUE THREAD

**Issue by clairexen** [YosysHQ-GmbH/blog_yosyshq#3]
https://github.com/YosysHQ-GmbH/blog_yosyshq/blob/22829e73707fdb01b73d49c3353481e3289a929b/config.yaml#L73-L79

Should we add Open Graph data? Something like the following:

```
    opengraph:
        twitter:
            site: @YosysHQ
            card: summary
```

I don't have a big opinion on `summary` vs `summary_large_image`, but I would assume that we will not have a fancy image for most blog posts. So I think it makes sense to go for the layout that shows a bit more of the text.

jfyi, this is a summary card  
![image](https://user-images.githubusercontent.com/59544343/119079904-63f61900-b9f9-11eb-9ec3-eb6313fa82de.png)

and this is summary_large_image  
![image](https://user-images.githubusercontent.com/59544343/119079971-86883200-b9f9-11eb-9892-a3f010a25424.png)
